"""covid-wiki

Revision ID: be7db691b25e
Revises: 
Create Date: 2020-04-18 14:55:40.336016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7db691b25e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid_wiki',
    sa.Column('territory_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('country', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.VARCHAR(length=128), nullable=True),
    sa.Column('confirmed', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('recovered', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('territory_id')
    )
    op.create_index('ix_covid_wiki_country', 'covid_wiki', ['country'], unique=False)
    op.create_index('ix_covid_wiki_state', 'covid_wiki', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_covid_wiki_state', table_name='covid_wiki')
    op.drop_index('ix_covid_wiki_country', table_name='covid_wiki')
    op.drop_table('covid_wiki')
    # ### end Alembic commands ###
